VAR TopItems =
    TOPN (
        3,
        VALUES ( ITEM_MASTER[item_number] ),
        [TOTAL_SALE], DESC,
        ITEM_MASTER[item_number], ASC
    )
VAR ThirdItem =
    EXCEPT ( TopItems, TOPN ( 2, TopItems, [TOTAL_SALE], DESC ) )
RETURN
    CALCULATE (
        SELECTEDVALUE ( ITEM_MASTER[img_url] ),
        ThirdItem
    )
