services:
  service_json_to_client_circlek:
    build:
      context: ../../../../..
      dockerfile: source/code/service/etl/service_json_to_client/Dockerfile
    container_name: service_json_to_client_circlek
    env_file:
      - .env
    environment:
      RUNNER_MODULE: libraries.runners.module_sequence
      RUNTIME_NAMESPACE: service_json_to_client
      SERVICE_NAME: service_json_to_client_circlek
    volumes:
      - ./app:/app/app
      - ../../../runtime_definitions/service_json_to_client:/app/runtime_definitions/service_json_to_client
      - ../../../../../resource/json/datafordeler:/app/resource/json/datafordeler
    networks:
      - data_network
    command: ["poetry", "run", "python", "app/main.py"]
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 1
        window: 30s

networks:
  data_network:
    external: true
