from .dagi_kommuneinddeling import main
from .dagi_landsdel import main
from .dagi_postnummeriddeling import main
from .dagi_region import main
from .dagi_storkreds import main
from .dar_adresse import main
from .dar_adressepunkt import main
from .dar_husnummer import main
from .dar_navngivenvej import main
from .dar_postnummer import main
from .simu_customer_cards import main
from .simu_products import main
from .simu_campaignsgroups import main
from .simu_cashier import main
from .simu_segmentationgroups import main
from .simu_transactions import main
from .stations import main