CREATE TABLE IF NOT EXISTS "datafordeler"."dar_husnummer"
(
    "id" text NOT NULL,
    "adgangsadressebetegnelse" text,
    "husnummerretning" text,
    "husnummertekst" text,
    "adgangspunkt_id" text,
    "vejpunkt_id" text,
    "jordstykke_id" text,
    "placeret_paa_foreloebigt_jordstykke" text,
    "geo_danmark_bygning_id" text,
    "adgang_til_bygning" text,
    "adgang_til_teknisk_anlaeg" text,
    "vejmidte_id" text,
    "afstemningsomraade_id" text,
    "kommuneinddeling_id" text,
    "supplerende_bynavn" text,
    "navngiven_vej_id" text,
    "postnummer_id" text,
    "id_namespace" text,
    "status" text,
    "virkning_fra" timestamp without time zone,
    "virkning_til" timestamp without time zone,
    "virkningsaktoer" text,
    "registrering_fra" timestamp without time zone,
    "registrering_til" timestamp without time zone,
    "registreringsaktoer" text,
    "datafordeler_opdateringstid" timestamp without time zone,
    "updatetime" timestamp without time zone,
    "createdtime" timestamp without time zone,
    CONSTRAINT "dar_husnummer_pkey" PRIMARY KEY (id)
);
