CREATE TABLE IF NOT EXISTS "default_data"."d_date"
(
    "date_dim_id" integer NOT NULL,
    "date_actual" date NOT NULL,
    "epoch" bigint NOT NULL,
    "day_suffix" character varying(4) NOT NULL,
    "day_name" character varying(9) NOT NULL,
    "day_of_week" integer NOT NULL,
    "day_of_month" integer NOT NULL,
    "day_of_quarter" integer NOT NULL,
    "day_of_year" integer NOT NULL,
    "week_of_month" integer NOT NULL,
    "week_of_year" integer NOT NULL,
    "week_of_year_iso" character(10) NOT NULL,
    "month_actual" integer NOT NULL,
    "month_name" character varying(9) NOT NULL,
    "month_name_abbreviated" character(3) NOT NULL,
    "quarter_actual" integer NOT NULL,
    "quarter_name" character varying(9) NOT NULL,
    "year_actual" integer NOT NULL,
    "first_day_of_week" date NOT NULL,
    "last_day_of_week" date NOT NULL,
    "first_day_of_month" date NOT NULL,
    "last_day_of_month" date NOT NULL,
    "first_day_of_quarter" date NOT NULL,
    "last_day_of_quarter" date NOT NULL,
    "first_day_of_year" date NOT NULL,
    "last_day_of_year" date NOT NULL,
    "mmyyyy" character(6) NOT NULL,
    "mmddyyyy" character(10) NOT NULL,
    "weekend_indr" boolean NOT NULL,
    CONSTRAINT "d_date_date_dim_id_pk" PRIMARY KEY (date_dim_id)
);
