from dotenv import load_dotenv
import os

load_dotenv(override=True, verbose=True)

# POSTGRESQL DATABASE
_POSTGRES_HOST = os.getenv("POSTGRES_HOST")
_POSTGRES_PORT = os.getenv("POSTGRES_PORT")
_POSTGRES_USERNAME = os.getenv("POSTGRES_USERNAME")
_POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
assert _POSTGRES_HOST
assert _POSTGRES_PORT
assert _POSTGRES_USERNAME
assert _POSTGRES_PASSWORD
POSTGRES_HOST = _POSTGRES_HOST
POSTGRES_PORT = _POSTGRES_PORT
POSTGRES_USERNAME = _POSTGRES_USERNAME
POSTGRES_PASSWORD = _POSTGRES_PASSWORD

# DATAFORDELER
_DATAFORDELER_USER = os.getenv("DATAFORDELER_USER")
_DATAFORDELER_PASSWORD = os.getenv("DATAFORDELER_PASSWORD")
_DATAFORDELER_API_KEY = os.getenv("DATAFORDELER_API_KEY")
assert _DATAFORDELER_USER
assert _DATAFORDELER_PASSWORD
assert _DATAFORDELER_API_KEY
DATAFORDELER_PASSWORD = _DATAFORDELER_PASSWORD
DATAFORDELER_USER = _DATAFORDELER_USER
DATAFORDELER_API_KEY = _DATAFORDELER_API_KEY
